spring:
  init:
    mode: never
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    changeLog: "classpath:db/changelog-prod.sql"